### ISSUE TITLE
go run knative.dev/toolbox/kntest/cmd/kntest@latest fails

### ISSUE THREAD

**Issue by nak3** [knative/toolbox#14]
As per title, the command produces an error:

```
$ go run knative.dev/toolbox/kntest/cmd/kntest@latest
go: knative.dev/toolbox/kntest/cmd/kntest@latest (in knative.dev/toolbox/kntest@v0.0.0-20230406165419-0318b24a34cf):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

Also CI - https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_hack/297/integration-tests_hack_main/1677125496590045184

**Comment by cardil** [comment]
Yes, we know about it. However, thanks for the bug report - great to have it for visibility.

I will describe this situation to make it clear.

After moving tools to this repo, we wanted to split their dependencies into submodels (Golang workspace) so that they would not affect each other in unpredictable ways. In the case of _kntest_, we awkwardly created a new module, but that it used common code the `replace` stanza was used (see https://github.com/knative/toolbox/pull/7). This caused the error described above - in Go you can't install, nor run packages that have the `replace` stanza.

Unfortunately, there is not much possibility to undo this operation, which we tried to do - see https://github.com/knative/toolbox/pull/9.

Currently, our idea going forward is to remove all kntest, in favor of using kubetest directly - this is led by @upodroid 

/assign @upodroid 

Alternatively, we could restore _kntest_ in this repo by copying all required packages, to avoid using the `replace` stanza, but I don't know is it worth it.

**Comment by upodroid** [comment]
We can delete this now. I already rolled out that change

**Comment by cardil** [comment]
If so, we can just delete the kntest directory in this project, right?

**Comment by upodroid** [comment]
yes, also need to delete the step that install kntest in the prow-tests image
